version: '3.1'

services:
  db:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

